### ISSUE TITLE
Useful info re: DNS and Internet Connection Sharing

### ISSUE THREAD

**Issue by btc-ss** [Xyl0se/Pwnagotchi-new-guerilla-guide#3]
Source: 

https://www.reddit.com/r/pwnagotchi/comments/dlvv47/comment/f5oudsp/

Thank you for the advice. Yes, you are right, I shouldn't be just running scripts without reading them. As for the requested information, here it is:

Screenshot of Windows host's RNDIS adapter: https://imgur.com/CrNP3UX
I have to mention that the Default gateway is blank as every time I try to set it to [10.0.0.1](https://10.0.0.1/) it reverts it back to blank (is it possible that something else has that gateway assigned?)

Screenshot of the Pi's configurations: https://imgur.com/nT02b2q

Can I ping [10.0.0.2](https://10.0.0.2/) from my host PC? - Yes (https://imgur.com/JVneT33)

Upvote
1

Downvote

Reply
reply

Share
Share

u/dan000892 avatar
dan000892
•
4 yr. ago
Well, we've certainly confirmed local network connectivity so the issue is unfortunately with Internet Connection Sharing on your Windows host which the Googles suggest is more of an issue when sharing a wireless connection than wired...

As there's just too many possible causes for this, you may have to resort to Googleing/StackExchange-ing and trying things other people with a similar issue have found to help.

My last-ditch suggestions are going to be:

Go to services.msc and confirm the Internet Connection Sharing service Startup Type is not Disabled and its Status is currently Running. (If it is Disabled, set it to Automatic. If it's not Running, start it.)

Try turning ICS off and on again. The script has parameters to do this:
.\win_connection_share -DisableInternetConnectionSharing
.\win_connection_share -EnableInternetConnectionSharing

Go through the manual GUI steps of sharing your wireless network connection which are horribly obtuse and vary by build so good luck. After doing this you may need to re-assert the Pwnagotchi subnet with .\win_connection_share.ps1 -SetPwnagotchiSubnet

Here's a PowerShell snippet from the win_connection_share script that'll determine if the subnet was reverted to the Windows default and tell you to run the SetPwnagotchiSubnet function.
$RegKeys = Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters -ErrorAction Stop
If ($RegKeys.ScopeAddress -notmatch '10.0.0.') {Write-Error "By default Internet Connection Sharing uses a 192.168.137.x subnet. Run Set-PwnagotchiSubnet to ensure you and your little friend are on the same subnet." -ErrorAction Stop}
If ($RegKeys.ScopeAddressBackup -notmatch '10.0.0.') { Write-Error "By default Internet Connection Sharing uses a 192.168.137.x subnet. Run Set-PwnagotchiSubnet to ensure you and your little friend are on the same subnet." -ErrorAction Stop}

Upvote
4

Downvote

Reply
reply

Share
Share

boggogo
•
4 yr. ago
Thank you! I managed to get my WiFi Intenet sharing working! I did the following:

I confirmed that my `Internet Connection Sharking` service is running

I run the script as suggesting first disabling the ICS and then enabling it

After the above I was able to ping from the pi (after I SSHed into it) just fine

**Comment by btc-ss** [comment]
source:

https://lazyadmin.nl/powershell/running-scripts-is-disabled-on-this-system/

In Powershell (admin mode):

1) powershell -ExecutionPolicy Bypass -File win_connection_share.ps1 -DisableInternetConnectionSharing
2) powershell -ExecutionPolicy Bypass -File win_connection_share.ps1 -EnableInternetConnectionSharing

**Comment by Xyl0se** [comment]
Thanks for the additional information
