### ISSUE TITLE
Soft carrying case

### ISSUE THREAD

**Issue by cantcodesheet** [Xyl0se/Pwnagotchi-new-guerilla-guide#4]
https://www.amazon.com/RISETECH-Headphone-Compatible-Powerbeats-Carabiner/dp/B08S7DFR57/ref=pd_aw_fbt_img_sccl_1/133-0955611-1804811?pd_rd_w=jQP5M&content-id=amzn1.sym.5debaa41-6f95-4fcb-bc98-9bd5c3197fd2&pf_rd_p=5debaa41-6f95-4fcb-bc98-9bd5c3197fd2&pf_rd_r=G2DAWJCZXTAQAJF7YJC6&pd_rd_wg=sIqQI&pd_rd_r=b619f34c-019f-4b35-bc8d-331c9def84e5&pd_rd_i=B08S7DFR57&psc=1

**Comment by Xyl0se** [comment]
Thanks for the recommendation, closing this issue for now
