### ISSUE TITLE
This guide inspired a Pwnagotchi wiki

### ISSUE THREAD

**Issue by V0r-T3x** [Xyl0se/Pwnagotchi-new-guerilla-guide#5]
After starting to adding new infos to this guide, I took the initiative to start a Pwnagotchi wiki, to make a big community knowledge base. The goal is to have a knowledge base from the noob level to a dev level. If anybody want to contribute, feel free to contact me, I will update it ASAP.

## [Pwnagotchi Wiki](https://github.com/V0r-T3x/pwnagotchi/wiki)

**Comment by Xyl0se** [comment]
Hey V0r-T3x thanks for the information. Glad to see this being put to use, albeit I did neglect the repository for the past year

**Comment by V0r-T3x** [comment]
@Xyl0se and now we have a community webpage (if you didnt see that) the [pwnagotchi.org](https://pwnagotchi.org/). Anybody from the community can contribute by PR from the [unofficial pwnagotchi org github](https://github.com/Pwnagotchi-Unofficial/Pwnagotchi.org).

**Comment by Xyl0se** [comment]
Closing this issue for now
